FROM python:3.7.9

RUN export DEBIAN_FRONTEND=noninteractive
# installing netcat (nc) since we are using that to listen to postgres server in entrypoint.sh
RUN apt-get update && apt-get install -yq --no-install-recommends netcat && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# set work directory
WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt .

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

RUN rm -rf /tmp/socket/*
RUN mkdir -p /tmp/socket/

COPY ./wait-for .
RUN mv wait-for /bin/wait-for
RUN ["chmod", "+x", "/bin/wait-for"]
RUN apt-get update ##[edited]
RUN apt-get install ffmpeg libsm6 libxext6  -y
